server:
  port: 8080


spring:
    datasource:
        name: mysql_ink
        type: com.zaxxer.hikari.HikariDataSource
        #HikariCP相关配置
        hikari:
          #基本属性
          jdbc-url: jdbc:mysql://127.0.0.1:3306/ink?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: root
          #连接池大小名称等
          maximum-pool-size: 5
          connection-test-query: SELECT 1
          pool-name: ink
          auto-commit: true
    thymeleaf:
            prefix: classpath:/templates/
            check-template-location: true
            suffix: .html
            encoding: UTF-8
            mode: LEGACYHTML5
            cache: false
    aop:
      auto: true
      proxy-target-class: true
    servlet:
          multipart:
            max-file-size: 10Mb
            max-request-size: 100Mb


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.itao.domain.entity


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

logging:
  level:
    cn.luischen.dao : DEBUG

swagger:
  show: true